export const emojiReactions = [
    { name: 'smile', emoji: '😀' },
    { name: 'thumb', emoji: '👍' },
    { name: 'heart', emoji: '❤️' },
    { name: 'OK', emoji: '👌' },
    { name: 'laugh', emoji: '😂' },
    { name: 'sad', emoji: '😢' },
    { name: 'angry', emoji: '😠' },
    { name: 'surprised', emoji: '😲' },
    { name: 'cool', emoji: '😎' },
    { name: 'wink', emoji: '😉' },
    { name: 'kiss', emoji: '😘' },
    { name: 'hug', emoji: '🤗' },
    { name: 'clap', emoji: '👏' },
    { name: 'fire', emoji: '🔥' },
    { name: 'boom', emoji: '💥' },
    { name: 'party', emoji: '🎉' },
    { name: 'star', emoji: '⭐' },
    { name: 'rocket', emoji: '🚀' },
];
